[build]
  command = "npm run build"
  publish = "dist/public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/logo512.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/json"